// import { cssStyle } from "./page.css";
import type { Metadata } from "next";
import { Suspense } from "react";
import { Footer } from "@/component/Footer";
import { FooterButton } from "@/component/FooterButton";
import { Header } from "@/component/Header";
import { About } from "@/component/Top/About";
// import { ContactUs } from "@/component/Top/ContactUs";
import { Case } from "@/component/Top/Case";
// import { Menu } from "@/component/Top/Menu";
import { Mv } from "@/component/Top/Mv";
import { Reserve } from "@/component/Top/Reserve";
// import { News } from "@/component/Top/News";
// import { Reserve } from "@/component/Top/Reserved";
// import { ShopInfo } from "@/component/Top/ShopInfo";

export const metadata: Metadata = {
  title:
    "爪甲鉤彎症（そうこうこうわんしょう）の経験者が開いたフットケアサロン 爪と足と",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main>
        <Suspense>
          <Header pageId="top" />
        </Suspense>
        <Mv />
        {/* <News /> */}
        <About />
        <Case />
        <Reserve />
        {/* <div className={cssStyle.menuWrap}>
          <Menu />
          <ShopInfo />
          <Reserve />
          <ContactUs />
        </div> */}
        <Footer pageId="top" />
        <FooterButton pageId="top" />
      </main>
    </>
  );
}
