import type { Metadata } from "next";
import { Suspense } from "react";
import { Footer } from "@/component/Footer";
import { FooterButton } from "@/component/FooterButton";
import { Header } from "@/component/Header";
import { About } from "@/component/Top/About";
import { Case } from "@/component/Top/Case";
import { Mv } from "@/component/Top/Mv";
import { Reserve } from "@/component/Top/Reserve";

export const metadata: Metadata = {
  title:
    "爪甲鉤彎症（そうこうこうわんしょう）の経験者が開いたフットケアサロン 爪と足と",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main>
        <Suspense>
          <Header pageId="top" />
        </Suspense>
        <Mv />
        <About />
        <Case />
        <Reserve />
        <Footer pageId="top" />
        <FooterButton pageId="top" />
      </main>
    </>
  );
}
