name: Check install & lint & build

on:
  pull_request:

permissions:
  pull-requests: write # approve/merge に必要
  contents: write # merge に必要
  repository-projects: write # PRタイトル変更等に必要

jobs:
  check-ci:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 13
    steps:
      - name: Dependabot metadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version-file: ".node-version"

      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_MICROCMS_API_KEY: ${{ secrets.NEXT_PUBLIC_MICROCMS_API_KEY }}
          NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN: ${{ secrets.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN }}
          NEXT_PUBLIC_CONTENT_ID_ABOUT: ${{ secrets.NEXT_PUBLIC_CONTENT_ID_ABOUT }}
          NEXT_PUBLIC_CONTENT_ID_RESERVE: ${{ secrets.NEXT_PUBLIC_CONTENT_ID_RESERVE }}
          NEXT_PUBLIC_CONTENT_ID_SHOPINFO: ${{ secrets.NEXT_PUBLIC_CONTENT_ID_SHOPINFO }}
          NEXT_PUBLIC_CONTENT_ID_TERMS: ${{ secrets.NEXT_PUBLIC_CONTENT_ID_TERMS }}
          NEXT_PUBLIC_CONTENT_ID_CASELIST: ${{ secrets.NEXT_PUBLIC_CONTENT_ID_CASELIST }}
          NEXT_PUBLIC_API_ENDPOINT_SHOPINFO: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT_SHOPINFO }}
          NEXT_PUBLIC_API_ENDPOINT_MENU: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT_MENU }}
          NEXT_PUBLIC_API_ENDPOINT_TREATMENT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT_TREATMENT }}

      - name: Lint
        run: npm run lint
