name: Build Check

on:
  # 手動実行
  workflow_dispatch:

jobs:
  Build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    concurrency:
      group: production_rule_build
      cancel-in-progress: true

  Deploy:
    name: Deploy
    uses: ./.github/workflows/_deploy_check.yml
    secrets: inherit
    needs: Build
